version: '3'
services:
  object-classification-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: object-classification-api
    image: fc
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    networks:
      - object-classification-api_network
    command: ["sh","-c","gunicorn -w 4 -b 0.0.0.0:5000 wsgi:app"]
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_DEBUG: ${FLASK_DEBUG}

networks:
  object-classification-api_network:
    name: object-classification-api_network
    driver: bridge
